import {Noto_Sans} from "next/font/google";
import "./globals.css";
import AuthProvider from "@/lib/AuthProvider";
import React from "react";
import CandidateEmployerData from "@/Context/Candidate_Employer_Data";


const notoSans = Noto_Sans({subsets: ["latin"]});

export const metadata = {
    title: "CareerSync", description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (<html className="scroll-smooth" lang="en">
    <body className={`${notoSans.className}`}>
        <CandidateEmployerData>
            <AuthProvider>
                {children}
            </AuthProvider>
        </CandidateEmployerData>
    </body>
    </html>);
}
