import {Noto_Sans} from "next/font/google";
import "./globals.css";
import AuthProvider from "@/lib/AuthProvider";
import React from "react";


const notoSans = Noto_Sans({subsets: ["latin"]});

export const metadata = {
    title: "CareerSync", description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (<html lang="en">
    <body className={notoSans.className}>
        <AuthProvider>
            {children}
        </AuthProvider>
    </body>

    </html>);
}
